import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { normalizePoseSequence } from '../core/poseMotion.js';

export class MotionReferenceStore {
  constructor(filePath = process.env.MOTION_REFERENCE_LIBRARY_PATH || './data/motion-references.json') {
    this.filePath = filePath;
  }

  async list() {
    try {
      const parsed = JSON.parse(await readFile(this.filePath, 'utf8'));
      const items = Array.isArray(parsed)
        ? parsed
        : Array.isArray(parsed?.references)
          ? parsed.references
          : [];
      return items.map(normalizeReference).filter(Boolean);
    } catch (error) {
      if (error?.code === 'ENOENT') return [];
      throw error;
    }
  }

  async write(references = []) {
    const normalized = references.map(normalizeReference).filter(Boolean);
    await mkdir(path.dirname(this.filePath), { recursive: true });
    const temporary = `${this.filePath}.${process.pid}.tmp`;
    await writeFile(temporary, JSON.stringify({ references: normalized }, null, 2) + '\n');
    await rename(temporary, this.filePath);
    return normalized;
  }
}

export function normalizeReference(input) {
  if (!input || typeof input !== 'object') return null;
  const url = String(input.url || '').trim();
  const localPath = String(input.localPath || '').trim();
  const validUrl = /^https:\/\//i.test(url)
    || /^data:video\/[a-z0-9.+-]+;base64,/i.test(url);
  if (!validUrl && !localPath) return null;

  const durationSeconds = Number(input.durationSeconds);
  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0 || durationSeconds > 15) {
    return null;
  }

  const actionClass = normalizeToken(input.actionClass || input.action || 'general');
  const tags = [...new Set((Array.isArray(input.tags) ? input.tags : [])
    .map(normalizeToken)
    .filter(Boolean))]
    .slice(0, 20);

  const poseSequence = input.poseSequence
    ? normalizePoseSequence({
      ...input.poseSequence,
      durationSeconds: input.poseSequence.durationSeconds || durationSeconds,
    })
    : null;

  return {
    id: String(input.id || `${actionClass}-${url.slice(-18)}`).slice(0, 120),
    actionClass,
    tags,
    cameraMode: normalizeToken(input.cameraMode || input.camera || 'any'),
    people: clampInt(input.people, 1, 8, 1),
    durationSeconds: Math.round(durationSeconds * 1000) / 1000,
    url: validUrl ? url : '',
    localPath,
    source: String(input.source || '').slice(0, 300),
    license: String(input.license || '').slice(0, 180),
    notes: String(input.notes || '').slice(0, 500),
    verifiedHumanMotion: input.verifiedHumanMotion !== false,
    rightsConfirmed: input.rightsConfirmed === true,
    poseSequence: poseSequence?.frames?.length ? {
      ...poseSequence,
      frames: poseSequence.frames.slice(0, 300),
      contacts: poseSequence.contacts.slice(0, 32),
    } : null,
    qualityScore: clampNumber(input.qualityScore, 0, 100, 0),
    classificationConfidence: clampNumber(input.classificationConfidence, 0, 1, 0),
    autoGenerated: input.autoGenerated === true,
    sourceClip: String(input.sourceClip || '').slice(0, 500),
    segmentStartSeconds: clampNumber(input.segmentStartSeconds, 0, 36000, 0),
    segmentEndSeconds: clampNumber(input.segmentEndSeconds, 0, 36000, durationSeconds),
    createdAt: String(input.createdAt || '').slice(0, 64),
  };
}

function normalizeToken(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function clampInt(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(min, Math.min(max, Math.round(number)));
}


function clampNumber(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(min, Math.min(max, number));
}
